version: '3.9'

services:
  backend:
    image: nestapp:1.0.0
    container_name: mini_ecomerce_system
    build: .
    ports:
      - "3001:3001"
    restart: always
    working_dir: /app
    volumes:
      - ./:/app
    environment:
      - JWT_SECRET=jwt_secret
      - MONGO_DB_URL=mongodb+srv://mongo:8jPVCjHierlKyooi@cluster0.urfcy2p.mongodb.net/?retryWrites=true&w=majority
      - PORT=3001
    depends_on:
      - db
  db:
    image: mongo:5.0.7
    container_name: mini_ecomerce_system_db
    ports:
      - "3002:27017"
